In [1]:
import numpy as np
import time

In [2]:
lst = list(range(1000000))
arr =np.arange(1000000)

In [5]:
start =time.time()
sum(lst)
print(f"list time = {time.time() - start}")

start = time.time()
np.sum(arr)
print(f"Numpy time = {time.time() - start}")

list time = 0.007837772369384766
Numpy time = 0.0008730888366699219


## Ndarray - The Heart of Numpy

In [11]:
arr1 = np.array([1,2,3,4])
print("1D array:\n",arr1) 

1D array:
 [1 2 3 4]


In [12]:
arr2 = np.array([[1,2,3],[4,5,6]])
print("2D array:\n", arr2)

2D array:
 [[1 2 3]
 [4 5 6]]


#### Array of zeros, ones, range

In [14]:
zeros = np.zeros((2,3))
zeros

array([[0., 0., 0.],
       [0., 0., 0.]])

In [15]:
ones =np.ones((3,3))
ones

array([[1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.]])

In [ ]:
range_array = np.arange(0,10,2)
print("Range array: ",