In [1]:
import numpy as np
import time

In [2]:
lst = list(range(1000000))
arr =np.arange(1000000)

In [5]:
start =time.time()
sum(lst)
print(f"list time = {time.time() - start}")

start = time.time()
np.sum(arr)
print(f"Numpy time = {time.time() - start}")

list time = 0.007837772369384766
Numpy time = 0.0008730888366699219


## Ndarray - The Heart of Numpy

In [11]:
arr1 = np.array([1,2,3,4])
print("1D array:\n",arr1) 

1D array:
 [1 2 3 4]


In [12]:
arr2 = np.array([[1,2,3],[4,5,6]])
print("2D array:\n", arr2)

2D array:
 [[1 2 3]
 [4 5 6]]


#### Array of zeros, ones, range

In [14]:
zeros = np.zeros((2,3))
zeros

array([[0., 0., 0.],
       [0., 0., 0.]])

In [15]:
ones =np.ones((3,3))
ones

array([[1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.]])

In [16]:
range_array = np.arange(0,10,2)
print("Range array: ", range_array)

Range array:  [0 2 4 6 8]


#### Array Operations

In [18]:
array_a =  np.array([1,2,3])
array_b = np.array([10,20,30])
array_a , array_b

(array([1, 2, 3]), array([10, 20, 30]))

In [23]:
# Element-wise operations
print(array_a+array_b)  # Addition
print(array_a-array_b)  # Subraction
print(array_a*array_b)  # Multiplication
print(array_b/array_a)  # Divivsion
print(array_a**2)       # Exponential

[11 22 33]
[ -9 -18 -27]
[10 40 90]
[10. 10. 10.]
[1 4 9]


In [27]:
# Broadcasting
matrix =np.array([[1,2,3],[4,5,6]])
print("Normal:\n", matrix)
print("Broadcasted:\n",matrix + 5)

Normal:
 [[1 2 3]
 [4 5 6]]
Broadcasted:
 [[ 6  7  8]
 [ 9 10 11]]


## Indexing, Slicing, Reshaping

In [28]:
# Indexing
mat =np.array([[10,20,30],[40,50,60]])
print(mat[1][1])

50


In [33]:
# Slicing
print(mat[::-1,::-1])

[[60 50 40]
 [30 20 10]]


In [36]:
# Reshaping
reshaped_array = np.arange(12).reshape(3,4)
reshaped_array

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

In [39]:
reshaped_mat = np.reshape(mat,(3,2))
reshaped_mat

array([[10, 20],
       [30, 40],
       [50, 60]])

## Useful Numpy Functions

In [42]:
# mean
arr = np.array([4,7,3,67,2,8])
print(np.mean(arr))

15.166666666666666


In [43]:
# Standard Deviation
print(np.std(arr))

23.276717027011255


In [44]:
# Sort
print(np.sort(arr))

[ 2  3  4  7  8 67]


In [45]:
# Linespace
lin =np.linspace(0,3,8)
print(lin)

[0.         0.42857143 0.85714286 1.28571429 1.71428571 2.14285714
 2.57142857 3.        ]


In [47]:
# Random
rand = np.random.randint(1,10, (4,5))
print(rand)

[[1 1 2 7 2]
 [4 5 1 4 5]
 [2 2 7 6 1]
 [3 9 8 7 3]]
